name: Cypress test
on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Which branch to checkout and run test'
        required: false
        default: master

jobs:
  checkout-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      
      - name: Run cypress tests
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
